server.port=8086
spring.application.name=rabbitmq-admin-service

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

rabbitmq.management.base-url=http://localhost:15672/api
rabbitmq.management.username=admin
rabbitmq.management.password=admin123